### ISSUE TITLE
Tutorial uses POST with SimpleHTTPServer

### ISSUE THREAD

**Issue by simonwhitaker** [reactjs/react-tutorial#1]
The tutorial suggests [using `python -m SimpleHTTPServer`](http://facebook.github.io/react/docs/tutorial.html#updating-state) to serve content, but subsequently introduces a mechanism for [submitting comments via a POST request](http://facebook.github.io/react/docs/tutorial.html#callbacks-as-props), which `SimpleHTTPServer` doesn't support. It appears that at this point the tutorial assumes you're using the sample node.js server packaged with [the tutorial's GitHub repo](https://github.com/reactjs/react-tutorial) but that isn't explained.

**Comment by ilmoralito** [comment]
501 error when try to post comments using python -m simpleHTTPServer as a server, i can see node, python, ruby servers in repo but i think this should be pointed in documentation

**Comment by renaldow** [comment]
I ran into the same 501 error using the POST request in the simpleHTTPServer method. Thanks for creating a PR simonwhitaker.

**Comment by AndrewSouthpaw** [comment]
+1 to Simon's PR. Looks like everything is there. I actually wrote out my own solution before learning (through Simon) that a server solution already exists in the repo.

**Comment by tbredin** [comment]
This caused me about 2 hours of despair, sure I'd done everything right before finally realising the server recommended in the article just didn't support post (thanks simon!)
A simple "Note:" message in the tutorial would save users a lot of confusion, explaining that they'll need a better server that supports POST in order to save comments

**Comment by chenglou** [comment]
@zpao kinda lost track here, what's happening?

**Comment by zpao** [comment]
https://github.com/facebook/react/pull/2824, which is similar to @simonwhitaker's PR. Or we could go back to his and tweak it some.

**Comment by zpao** [comment]
Updating the website shortly with newer docs so this is fine to close now.

**Comment by hellyeah** [comment]
Someone should just link to this issue in the tutorial.
