### ISSUE TITLE
Warning: React.render is deprecated. 

### ISSUE THREAD

**Issue by angeliaz** [reactjs/react-tutorial#108]
代码运行有这个报错：Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead. 不影响实际结果，想了解下，这是否表示 React.render已经被废弃了，改成了方法ReactDOM.render?

**Comment by angeliaz** [comment]
https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html
在这儿看到好像确实是新版本中修改了

**Comment by zpao** [comment]
This project was updated along with the release of 0.14 and uses `ReactDOM.render`
