### ISSUE TITLE
server.rb does not reload comments.json

### ISSUE THREAD

**Issue by theminted** [reactjs/react-tutorial#13]
The tutorial states that the file _comments.json will be reloaded with each request for '/comments.json'. However, server.rb only loads this file once before webbrick is started. Moving the loading and parsing of _comments.js into the block server.mount_proc '/comments.json' solves the problem.

**Comment by theminted** [comment]
Disregard this pullrequest. It disables the posting functionality.

**Comment by dominion79** [comment]
I having the same problem. I have to restart the server to get any changes to the *_comments.json* to take effect. I have tried using *server.rb* and *server.js* and its the same issue with both.

**Comment by theminted** [comment]
We figured out what the problem was and will push a fix soon.

**Comment by proever** [comment]
Hooray! Glad I checked here. I was wondering what I was doing wrong.

**Comment by zpao** [comment]
Fixed in all of the servers. Thanks for getting this started!
