### ISSUE TITLE
SecurityError: The operation is insecure browser.js 

### ISSUE THREAD

**Issue by yepzy** [reactjs/react-tutorial#135]
I have copy all of the file of the tutorial but I have an error and I can't find it 
`SecurityError: The operation is insecure  ....indexOf(k) === -1 && has.call(window, k) && window[k] !== null && typeof window...  browser.js (ligne 43387)`

PS: I am behind a proxy

**Comment by zpao** [comment]
This is happening inside the JSX transform tool (Babel's older in-browser transform) so nothing to do with your code. It's about the same origin policy - which I haven't seen be an issue as of yet. Perhaps the proxy has something to do with it. You could try downloading the file (which is currently being served from a CDN) and serve it locally.
