### ISSUE TITLE
Better visualisation of component hierarchy? 

### ISSUE THREAD

**Issue by lalwanivikas** [reactjs/react-tutorial#145]
I went through the tutorial recently and found it great!

One thing that I think can be improved for beginners is visualization of component hierarchy. It is very well described and visualized in [Step-1 of Thinking in React](https://facebook.github.io/react/docs/thinking-in-react.html#step-1-break-the-ui-into-a-component-hierarchy).

So I went ahead and added a little CSS to make it clear. Please see screenshots below. Do you think something like this will add value? If so, I would love to improve it a bit and submit a PR.

Thanks :)

**Before:**
![screen shot 2016-07-07 at 8 15 37 pm](https://cloud.githubusercontent.com/assets/9963169/16657312/ab0df352-447f-11e6-8dd7-71743bca0ebd.png)

**After:**
![screen shot 2016-07-07 at 8 08 54 pm](https://cloud.githubusercontent.com/assets/9963169/16657319/b47ce1be-447f-11e6-81d4-37989a60df60.png)

**Comment by spicyj** [comment]
I don't think we'll include something like this in the tutorial, but the React devtools let you browse the component tree and see the bounds of each component.
