### ISSUE TITLE
npmcdn can't find react js file

### ISSUE THREAD

**Issue by half-adder** [reactjs/react-tutorial#153]
NPMCDN can't find the version of the React JS file that is linked to in index.html.

I replaced the offending line with

`<script src="https://npmcdn.com/react/dist/react.min.js"></script>`

which downloads the latest version.

**Comment by zpao** [comment]
Must have been a hiccup or something with npmcdn as `https://npmcdn.com/react@15.3.0/dist/react.js` is loading fine. Glad you figured it out though!

**Comment by half-adder** [comment]
Cheers
