### ISSUE TITLE
Error undefined 

### ISSUE THREAD

**Issue by mikecasas** [reactjs/react-tutorial#44]
I am trying to walk through the tutorial and I am getting an error on section "tutorial3.js" when you add the comment list and comment form to the comment box.

I downloaded the starter kit and I am using the "Offline Transform" method to compile the jsx to plain javascript.

I uploaded the files to a repo.
http://mikecasas.github.io/react-tutorial

**Comment by mikecasas** [comment]
I finally figured it out, you need to place the React.render after the CommentList and CommentForm definitions.

**Comment by zpao** [comment]
Glad you figured it out. Good luck!
