### ISSUE TITLE
This is a minor issue:

### ISSUE THREAD

**Issue by zargold** [reactjs/react-tutorial#49]
I just was playing with the tutorial on node.js.

When it came right out of the box at least for me (I might be some edge case), the comments showed up with ,commas on either side of the comment body( or text), <like here. To fix this I adjusted rawMarkup to  apply the marked function on this.props.children[1].toString() rather than this.props.children.toString();

```
var Comment = React.createClass({
    render: function () {
        console.log(this.props.children[1]);
        var rawMarkup = marked(this.props.children[1].toString(), {
            sanitize: true
        });
    return ( 
        <div className="comment">
            <h2 className="commentAuthor"> {this.props.author}</h2> 
            <span dangerouslySetInnerHTML = {{__html: rawMarkup }}/>
        </div>
        );
    }
 });
```
I also made a few adjustments to the server (switching res.setHeader( application/json)+ res.send(data) to just res.json(data), but by reverting back and forth it didn't seem to make a difference.

```
app.use(bodyParser.json({ extended: false }));

app.get('/comments.json', function(req, res) {
  fs.readFile('comments.json', function(err, data) {
    //res.setHeader('Content-Type', 'application/json');
    console.log(data);
    res.json(data);
  });
});
```

**Comment by zpao** [comment]
I haven't seen this from anybody else so perhaps you hit some edge case. I'm going to close out but we can revisit if there are other reports.
