### ISSUE TITLE
Error 404 comments.json Not found

### ISSUE THREAD

**Issue by methuz** [reactjs/react-tutorial#54]
I downloaded react-tutorial then tried to run it using `python -m SimpleHTTPServer` or `http-server` but got this error. Note that I've already run `npm install` and `node server.js`

http-server
```
"GET /comments.json?_=1432976000368" Error (404): "Not found"
```
python -m SimpleHTTPServer
```
"GET /comments.json?_=1432976065093 HTTP/1.1" 404 -
```

I've tried in both root and public folder.

**Comment by methuz** [comment]
In my case, Problem solved by moving comments.json to public/.

Is there another way around?

**Comment by spicyj** [comment]
See the readme:

https://github.com/reactjs/react-tutorial#readme

Let me know if any of our docs said to use `python -m SimpleHTTPServer` or `http-server` and I'll get them changed.
