### ISSUE TITLE
I think this router should be app.get('/comments')

### ISSUE THREAD

**Issue by sleelily** [reactjs/react-tutorial#56]
```
app.get('/comments.json', function(req, res) {
  fs.readFile('comments.json', function(err, data) {
    res.setHeader('Content-Type', 'application/json');
    res.send(data);
  });
});
```
because when I use router file `index.js` default in Express demo,it is still work even if there is
no these code.
it seems need to delete the `.json`,and the html/jade file should be 
`<CommentBox url="/comments" pollInterval={20000} />`

**Comment by zpao** [comment]
See #39 and #48, which I should revisit at some point. If you're interested in moving this along a little bit, it would be helpful to audit the tutorial text in the react repo and making sure everything aligns.
