### ISSUE TITLE
Update script sources on tutorial page

### ISSUE THREAD

**Issue by cristovaov** [reactjs/react-tutorial#57]
Hi there,
Would it be possible to update [the tutorial](https://facebook.github.io/react/docs/tutorial.html) to the cloudflare script sources like in the repo? 
Perhaps the tutorial could be revised as a whole for consistency with these example files.
Cheers and thanks~

**Comment by zpao** [comment]
The tutorial docs are checked into the React repo. There shouldn't be too many differences between here and the content on the website, but if there are some things you'd like to see changes, I would take a PR :)

https://github.com/facebook/react/blob/master/docs/docs/tutorial.md

**Comment by cristovaov** [comment]
Ha, I was wondering were the doc repo was hiding (and somehow missed the link to it on the web page.. :$ ) Thanks for pointing me to it!
