### ISSUE TITLE
server.js problem

### ISSUE THREAD

**Issue by wdanxna** [reactjs/react-tutorial#65]
I don't know if I got something wrong here. but it seems like the handler for "comment.js" in Nodejs version of server code never been executed, instead, any GET request like "http://localhost:3000/comments.js" is treated as static file, just bypass the handler associated with router.

**Comment by zpao** [comment]
No, it works right. Feel free to add logging to the method and see that.

Also, we're only setting up the static handler for the `public/` directory.
