### ISSUE TITLE
Update for 0.14

### ISSUE THREAD

**Issue by zpao** [reactjs/react-tutorial#83]
@spicyj made some changes in the React repo to use ReactDOM. We should do that here too as well as bump versions to 0.14 once we ship.

**Comment by zorfling** [comment]
Yep, I'm trying to follow the tutorial, but it's for 0.14.0 and the starter code repo is for 0.13.0. (and the cdn doesn't have 0.14.0 yet?
For anyone else trying this in the interim, I just used the following scripts:
    <script src="https://fb.me/react-0.14.0.js"></script>
    <script src="https://fb.me/react-dom-0.14.0.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
