### ISSUE TITLE
tutorial8.js

### ISSUE THREAD

**Issue by nordbit** [reactjs/react-tutorial#86]
```
// tutorial8.js
var data = [
  {author: "Pete Hunt", text: "This is one comment"},
  {author: "Jordan Walke", text: "This is *another* comment"}
];
```
do not work

but
```
// tutorial8.js
var data = [
  {"author": "Pete Hunt", "text": "This is one comment"},
  {"author": "Jordan Walke", "text": "This is *another* comment"}
];
```
work correctly

**Comment by zpao** [comment]
What's error did you see? At that point in the tutorial we're just accessing that object directly and that is valid JS.

**Comment by nordbit** [comment]
Sorry, yesterday not work, today all work correctly, without any changes, no idea why.
Maybe gremlins escaped  from my PC at night.
