### ISSUE TITLE
Tutorial 3 - Runtime Errors

### ISSUE THREAD

**Issue by TheWobling** [reactjs/react-tutorial#87]
When trying to use the CommentList and CommentForm I receive these errors.

Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `CommentBox`.

Uncaught Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `CommentBox`.

      var CommentBox = React.createClass({
        render: function() {
          return (
            <div className="commentBox">
              <h1>Comments</h1>
              <CommentList />
              <CommentForm />
            </div>
          );
        }
      });
      ReactDOM.render(
        <CommentBox />,
        document.getElementById('content')
      );

Any help is greatly appreciated.

**Comment by TheWobling** [comment]
My Mistake, ReactDom needed to be at the end of the file.
  ReactDOM.render(
    <CommentBox />,
    document.getElementById('content')
  );

**Comment by flacoman91** [comment]
thanks for this. I was getting stuck too!

**Comment by carlpoole** [comment]
I just became a victim of this too.

**Comment by coollorenzo** [comment]
Thanks I read over it so I got also stuck on it
