### ISSUE TITLE
comment getting replaced rather than concatenating 

### ISSUE THREAD

**Issue by abhitheawesomecoder** [reactjs/react-tutorial#88]
comment get replaced rather than concatenating

**Comment by zpao** [comment]
Which server were you running and how did you run it?

**Comment by abhitheawesomecoder** [comment]
I buit it with browsifty and babelify and was running the bundle on xampp
server

**Comment by zpao** [comment]
So you did not just run `php server.php`? Right now that's our only supported way to run the PHP server in the tutorial. If you deviate, you'll want to ensure your server is providing the same functionality we have here. We provide a number of servers so you can focus on learning React and not worry about the server situation.

I can see you're running node (must be to use browserify + babel) so perhaps you'd be interested in just running the node server while you use the tutorial.
